### PR TITLE
Add AllConvNet

### PR DESCRIPTION
**Pull request by Shreyas-Bhat**

### CODE REVIEW

**Comment by someshsingh22** [comment]
@Shreyas-Bhat please lint as given in Contributing.md
Also add tests at tests/common/vision/models/test_allconv.py

**Comment by someshsingh22** [comment]
@Shreyas-Bhat your PR fails because its not matching black / isort standards.
Please lint your code properly with black, isort and flake to merge this.

**Comment by someshsingh22** [comment]
@Shreyas-Bhat modules are not a part of package because they are not imported in the __init__.py files check other __init__.py in models and tests/../models

**Comment by someshsingh22** [comment]
@Shreyas-Bhat Is this PR the same as #46 ? In that case I will close this PR

**Comment by Shreyas-Bhat** [comment]
> @Shreyas-Bhat Is this PR the same as #46 ? In that case I will close this PR

@someshsingh22 Yes, it is the same, you may close it

**Comment by someshsingh22** [comment]
Closing because its a duplicate of #46

**Pull request closed without merging**
