### PR TITLE
Seperate Linting workflow; Setup pre-commit

### LINKED ISSUE #10: CodeCoverage Report Missing
CodeCoverage Reports are missing

### PR DESCRIPTION
**Pull request by Devanshu24**
Mainly a PR to clean up the CI workflows and add a few more useful ones
Feedback/Suggestions are welcome!

Fixes #10

### CODE REVIEW

**Comment by Devanshu24** [comment]
@someshsingh22 Have a look, changed quite a few things but hopefully it should all work now

**Comment by someshsingh22** [comment]
We have changed the repository name in the latest PR #8, can you rename code-soup to code_soup ? Its causing issues in the Imports @Devanshu24

**Review by someshsingh22 — CHANGES_REQUESTED** [review]
the renaming is supposed to be code_soup for the time being

**Comment by someshsingh22** [comment]
@Devanshu24 Latest PR has caused some merge conflicts, you can overwrite them

**Comment by Devanshu24** [comment]
There will be lot of linting failures from #9 
I think we should resolve them after merging this, to avoid cluttering a single PR

**Comment by someshsingh22** [comment]
Great so I am merging this and we can set up a final cleanup

**Pull request merged**
